In [1]:
l = [1235, 15, 168, 996, -1234]

In [2]:
import numpy as np

In [3]:
a = np.array(l)

In [4]:
a

array([ 1235,    15,   168,   996, -1234])

In [5]:
l.pop()

-1234

In [6]:
l

[1235, 15, 168, 996]

In [7]:
a.mean()

236.0

In [8]:
#-------

In [9]:
a

array([ 1235,    15,   168,   996, -1234])

In [10]:
a[2:4]

array([168, 996])

In [11]:
c = a.copy()

In [12]:
c

array([ 1235,    15,   168,   996, -1234])